# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isthiskeanureeves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='picture',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.AddField(
            model_name='page',
            name='rating',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
