# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isthiskeanureeves', '0003_auto_20180322_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
    ]
