# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import isthiskeanureeves.models


class Migration(migrations.Migration):

    dependencies = [
        ('isthiskeanureeves', '0004_remove_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(default='null', upload_to=isthiskeanureeves.models.user_upload),
        ),
    ]
